In [1]:
import torch
import torchvision.models as models
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
from torch.utils.data.dataset import Dataset
import time

In [2]:
class SVHNModel(nn.Module):  #继承nn.Module
    def __init__(self):  #在__init__中，定义所需组件
        super(SVHNModel,self).__init__()
        self.cnn = nn.Sequential(
            nn.Conv2d(3,16,kernel_size = (3,3),stride=(2,2)),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(16,32,kernel_size=(3,3),stride=(2,2)),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        self.fc1 = nn.Linear(32*3*7, 11)
        self.fc2 = nn.Linear(32*3*7, 11)
        self.fc3 = nn.Linear(32*3*7, 11)
        self.fc4 = nn.Linear(32*3*7, 11)
        self.fc5 = nn.Linear(32*3*7, 11)
        self.fc6 = nn.Linear(32*3*7, 11)
    def forward(self,img):   #组装网络
        feat = self.cnn(img)
        feat = feat.view(feat.shape[0],-1)
        c1 = self.fc1(feat)
        c2 = self.fc2(feat)
        c3 = self.fc3(feat)
        c4 = self.fc4(feat)
        c5 = self.fc5(feat)
        c6 = self.fc6(feat)
        return c1, c2, c3, c4, c5, c6
model = SVHNModel()


In [3]:
print(model)

SVHNModel(
  (cnn): Sequential(
    (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(16, 32, kernel_size=(3, 3), stride=(2, 2))
    (4): ReLU()
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc1): Linear(in_features=672, out_features=11, bias=True)
  (fc2): Linear(in_features=672, out_features=11, bias=True)
  (fc3): Linear(in_features=672, out_features=11, bias=True)
  (fc4): Linear(in_features=672, out_features=11, bias=True)
  (fc5): Linear(in_features=672, out_features=11, bias=True)
  (fc6): Linear(in_features=672, out_features=11, bias=True)
)


In [ ]:
#VGG16模型


In [9]:
class BasicModule(torch.nn.Module):
    def __init__(self):
        super(BasicModule,self).__init__()
        self.model_name = str(type(self))
    def load(self,path):
        self.load_state_dict(torch.load(path))
    def save(self,name=None):
        if name is None:
            preix='checkpoints/' + self.model_name + '_'
            name = time.strftime(prefix + '%m%d_%H:%M:%S.pth')
        torch.save(self.state_dict(),name)
        return name
class Flat(torch.nn.Module):
    '''
    把输入reshape成（batch_size,dim_length）
    '''

    def __init__(self):
        super(Flat, self).__init__()
        #self.size = size

    def forward(self, x):
        return x.view(x.size(0), -1)

In [16]:
import PIL.Image as Image

In [17]:
path = r'F:\books_projects\projects_2020\datawhale\alidata\mchar_train'
img = Image.open(path + '\\' + '000000.png')

In [31]:
import numpy as np
imgdata = np.array(img)

In [37]:
imgdata = torch.tensor(imgdata)

In [41]:
#imgdata.size()
imgdata.view(imgdata.size(0),-1)

tensor([[108, 112,  98,  ..., 255, 255, 255],
        [110, 114, 100,  ..., 255, 255, 255],
        [112, 116, 101,  ..., 255, 255, 255],
        ...,
        [ 20,  21,  25,  ..., 255, 255, 255],
        [ 19,  23,  24,  ..., 255, 255, 255],
        [ 18,  22,  21,  ..., 255, 255, 255]], dtype=torch.uint8)

In [32]:
a = ny.arange(6).reshape(3,2) 

In [33]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [36]:
a.view()

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
torch.nn.init